export const categoriesData: string[] = [
    "Finance",
    "Education",
    "Food",
    "Jobs",
    "Entertainment",
    "Travel",
    "Art & Crafts",
    "Fitness & Wellness",
    "Home & Wellness",
    "Fiction & Fantasy",
    "Comedy",
    "History & Culture",
    "Theatre",
    "Environment",
    "Relationships",
    "Marketing",
    "Fitness", // Duplicate removed
    "Business",
    "Photography",
    "News and Politics",
    "Astrology",
    "Beauty and Makeup",
    "Cartoons",
    "Crypto",
    "Dance",
    "Design",
    "Fashion & Lifestyle",
    "Gaming",
    "Health",
    "Hobbies",
    "Mentorship",
    "Motivation",
    "Music",
    "Non-profit",
    "Parenting",
    "Pets & Animals",
    "Religion",
    "Spirituality",
    "Startups",
    "Technology",
  ];