import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/context/NextAuthSessionProvider";
import ProgressBarProvider from "@/context/ProgressBarProvider";
import { Toaster as ShadcnToast } from "@/components/ui/sonner";
import ReactHookFormProvider from "@/context/ReactHookFormProvider";
import Script from "next/script";
import DateProvider from "@/context/DateProvider";
import { ToastContainer as Toastify } from "react-toastify";
import { Toaster as HotToast } from "react-hot-toast";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} debug-screens`}>
        <ProgressBarProvider>
          <NextAuthSessionProvider>
            <ReactHookFormProvider>
              <DateProvider>
                <main className="min-h-screen w-full">{children}</main>
                <ShadcnToast />
                <Toastify
                  position="top-right"
                  autoClose={5000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
                />
                <HotToast position="top-center" reverseOrder={false} />
              </DateProvider>
            </ReactHookFormProvider>
          </NextAuthSessionProvider>
        </ProgressBarProvider>
      </body>
    </html>
  );
}
